name: go test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Caching
      uses: actions/cache@v2
      with:
        path: ~/go/pkg
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Test
      if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
      run: go test ./...
    - name: Test with code coverage
      if: matrix.os == 'ubuntu-latest'
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Code Coverage
      if: matrix.os == 'ubuntu-latest'
      run: bash <(curl -s https://codecov.io/bash)
